spring:
  profiles:
    active:
      - beta
---
spring:
  profiles: dev
  application:
    name: cloudconfig-test-dev
---
spring:
  profiles: default
  application:
    name: cloudconfig-test-default