spring:
  profiles:
    active:
      - beta
---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: cloud-config-test-client_run this one

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:edwin@localhost:7301/eureka
      register-with-eureka: false

info:
  app.name: cloud-config-client-dev
  company.name: edwin
---
server:
  port: 8102

spring:
  profiles: beta
  application:
    name: cloud-config-test-client_8102

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:edwin@localhost:7301/eureka
      register-with-eureka: false
  
info:
  app.name: cloud-config-client-beta
  company.name: edwin
