spring:
  profiles:
    active:
      - beta
---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: cloudconfig-test-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:edwin@localhost:7001/eureka
---
server:
  port: 8102

spring:
  profiles: beta
  application:
    name: cloudconfig-test-client-sorry!

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:edwin@eureka2:7002/eureka
